import React from 'react';
import { motion } from 'motion/react';
import { 
  Beef, 
  Bird, 
  Fish, 
  Milk, 
  Sprout, 
  ArrowRight, 
  CheckCircle2, 
  Info,
  TrendingUp,
  Layers,
  Zap,
  Wrench,
  Settings,
  Hammer,
  Trees,
  Bug,
  Leaf
} from 'lucide-react';
import { useLanguage } from '../LanguageContext';
import { cn } from '../utils';

const IntegratedFarming: React.FC = () => {
  const { t } = useLanguage();

  const handleDownloadPlan = (plan: any) => {
    const planText = `
INTEGRATED FARMING DETAILED PLAN: ${plan.title}
===================================================

DESCRIPTION:
${plan.description}

KEY BENEFITS:
${plan.benefits.map((b: string, i: number) => `${i + 1}. ${b}`).join('\n')}

STEP-BY-STEP IMPLEMENTATION GUIDE:
${plan.steps.map((s: string, i: number) => `Phase ${i + 1}: ${s}`).join('\n')}

INFRASTRUCTURE NEEDED:
- Proper housing/sheds based on the animal/crop type
- Water supply and drainage management systems
- Waste recycling mechanisms (e.g., biogas, compost pits)

FINANCIAL EXPECTATIONS:
- Expected ROI: 30-50% higher than monoculture
- Cost Reduction: Up to 40% reduction in external inputs (fertilizers/feed)
- Break-even Point: Typically 18-24 months

SUSTAINABILITY METRICS:
- Achieves zero-waste circular economy
- Reduces chemical dependencies
- Improves long-term soil health

*Generated by AgroConnect AI Integrated Farming Module*
    `;

    const blob = new Blob([planText], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `${plan.title.replace(/[^a-z0-9]/gi, '_').toLowerCase()}_detailed_plan.txt`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };

  const plans = [
    {
      title: t('cropDairyTitle') || 'Crop + Dairy Farming',
      icon: <Milk className="w-6 h-6 text-blue-600" />,
      description: t('cropDairyDesc') || 'The most common and profitable combination for small to medium farmers.',
      benefits: [
        'Animal manure serves as high-quality organic fertilizer for crops.',
        'Crop residues (straw, husks) provide free fodder for cattle.',
        'Daily income from milk sales provides consistent cash flow.',
        'Reduced dependence on chemical fertilizers.'
      ],
      steps: [
        'Allocate 10-20% of land for green fodder (Napier grass, Lucerne).',
        'Construct a well-ventilated shed with proper drainage.',
        'Start with 2-3 high-yielding breeds (Gir, Sahiwal, or Murrah buffalo).',
        'Set up a small biogas plant to process manure for cooking fuel and slurry.'
      ],
      color: 'bg-blue-50',
      borderColor: 'border-blue-100'
    },
    {
      title: t('cropPoultryTitle') || 'Crop + Poultry Farming',
      icon: <Bird className="w-6 h-6 text-amber-600" />,
      description: t('cropPoultryDesc') || 'High-density farming with quick returns and low initial land requirement.',
      benefits: [
        'Poultry droppings are extremely rich in Nitrogen and Phosphorus.',
        'Birds help in natural pest control by eating insects and larvae.',
        'Short production cycle (45 days for broilers, daily eggs for layers).',
        'Minimal water requirement compared to dairy.'
      ],
      steps: [
        'Build a predator-proof poultry house near the farm.',
        'Choose between Broilers (meat) or Layers (eggs) based on market demand.',
        'Implement "Deep Litter" system to create high-quality compost.',
        'Use farm-grown maize and grains as a base for poultry feed.'
      ],
      color: 'bg-amber-50',
      borderColor: 'border-amber-100'
    },
    {
      title: t('cropGoatTitle') || 'Crop + Goat/Sheep Farming',
      icon: <Beef className="w-6 h-6 text-emerald-600" />,
      description: t('cropGoatDesc') || 'Ideal for drylands and regions with limited water resources.',
      benefits: [
        'Goats are "poor man\'s cow" - low maintenance and high resilience.',
        'Excellent for utilizing wasteland and marginal lands.',
        'High demand for meat ensures easy marketability.',
        'Manure is easy to collect and apply to fields.'
      ],
      steps: [
        'Select breeds like Sirohi, Barbari, or Black Bengal.',
        'Ensure a dry, elevated area for the goat shed.',
        'Practice rotational grazing to prevent overgrazing.',
        'Focus on "Stall Feeding" using farm-grown fodder for faster weight gain.'
      ],
      color: 'bg-emerald-50',
      borderColor: 'border-emerald-100'
    },
    {
      title: 'Paddy + Fish + Duck Farming',
      icon: <Fish className="w-6 h-6 text-cyan-600" />,
      description: 'A highly productive aquatic system ideal for lowland or heavy rainfall regions.',
      benefits: [
        'Ducks control aquatic weeds and pests while aerating the water.',
        'Fish droppings provide rich nutrients for paddy crops.',
        'Tremendous increase in protein yield per hectare.',
        'Mutualistic relationship drastically reduces chemical inputs.'
      ],
      steps: [
        'Modify the paddy field by digging trenches (refuges) for fish during low water.',
        'Introduce ducklings and fingerlings approximately 15-20 days after transplanting rice.',
        'Build a duck house elevated over the pond so droppings fall directly into the water.',
        'Harvest sequentially: Fish and ducks first, followed by the paddy.'
      ],
      color: 'bg-cyan-50',
      borderColor: 'border-cyan-100'
    },
    {
      title: 'Agroforestry (Silviculture)',
      icon: <Trees className="w-6 h-6 text-green-700" />,
      description: 'Combining trees with agricultural crops or pasture to enhance microclimate and soil.',
      benefits: [
        'Trees provide long-term financial security (timber, fruits).',
        'Deep tree roots bring up leached nutrients for surface crops.',
        'Creates windbreaks and improves local biodiversity.',
        'Significantly improves carbon sequestration.'
      ],
      steps: [
        'Select fast-growing, nitrogen-fixing trees (e.g., Gliricidia) or high-value timber/fruit trees.',
        'Plant in wide alleyways (Alley Cropping) to allow machinery and light penetration.',
        'Grow shade-tolerant crops (like ginger or turmeric) underneath as the canopy closes.',
        'Prune trees regularly to manage shade and use prunings as green mulch.'
      ],
      color: 'bg-green-50',
      borderColor: 'border-green-100'
    },
    {
      title: 'Crop + Apiculture (Beekeeping)',
      icon: <Bug className="w-6 h-6 text-yellow-600" />,
      description: 'Integrating bee hives with flowering crops to boost pollination and honey harvest.',
      benefits: [
        'Increases crop yields significantly (up to 30%) through better pollination.',
        'Harvest raw honey, beeswax, and pollen as high-value secondary income.',
        'Requires very little land and low daily maintenance.',
        'Supports local ecosystem and biodiversity.'
      ],
      steps: [
        'Set up apiaries (bee boxes) in shaded, quiet locations near water sources.',
        'Synchronize crop planting (mustard, sunflower) to provide year-round forage.',
        'Avoid spraying chemical pesticides entirely, especially during flowering season.',
        'Harvest honey post-flowering using safe extraction methods.'
      ],
      color: 'bg-yellow-50',
      borderColor: 'border-yellow-100'
    },
    {
      title: 'Crop + Mushroom Cultivation',
      icon: <Sprout className="w-6 h-6 text-stone-600" />,
      description: 'Utilizing agricultural waste (straw/husks) to grow high-value edible mushrooms indoors.',
      benefits: [
        'Converts zero-value crop residue into a premium edible product.',
        'Can be done indoors vertically, requiring almost no field space.',
        'Spent mushroom compost is one of the highest grade organic fertilizers.',
        'Very short growth cycle (weeks) ensures fast cash turnover.'
      ],
      steps: [
        'Collect and sterilize straw/husks mathematically avoiding contamination.',
        'Inoculate the substrate with high-quality mushroom spawn (Oyster/Button).',
        'Incubate in a dark, humid room (25-30°C) until mycelium colonizes.',
        'Induce fruiting by altering light and humidity; harvest and compost the rest.'
      ],
      color: 'bg-stone-100',
      borderColor: 'border-stone-200'
    },
    {
      title: 'Crop + Sericulture (Silk)',
      icon: <Leaf className="w-6 h-6 text-lime-600" />,
      description: 'Cultivating mulberry plants specifically to rear silkworms for silk production.',
      benefits: [
        'Highly lucrative cash crop providing massive returns per acre.',
        'Mulberry stems/leaves can also serve as fodder or fuel in the off-season.',
        'Generates consistent employment for farm families indoors.',
        'Silkworm excreta is excellent organic manure.'
      ],
      steps: [
        'Establish a mulberry garden with high-yielding varieties (e.g., V1).',
        'Construct a hygienic, well-ventilated rearing house.',
        'Procure Disease-Free Layings (DFLs) of silkworm eggs from certified centers.',
        'Feed worms meticulously chopped mulberry leaves until they spin cocoons for harvest.'
      ],
      color: 'bg-lime-50',
      borderColor: 'border-lime-100'
    }
  ];

  return (
    <div className="space-y-12 pb-20">
      <header className="relative overflow-hidden bg-emerald-900 text-white p-10 rounded-[2.5rem] shadow-2xl">
        <div className="absolute top-0 right-0 w-64 h-64 bg-emerald-800 rounded-full -translate-y-1/2 translate-x-1/2 opacity-20" />
        <div className="relative z-10 max-w-2xl">
          <motion.div 
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            className="inline-flex items-center gap-2 px-4 py-2 bg-emerald-800/50 rounded-full text-xs font-bold uppercase tracking-widest mb-6 border border-emerald-700"
          >
            <Layers className="w-4 h-4" />
            {t('integratedFarming') || 'Integrated Farming'}
          </motion.div>
          <h1 className="text-4xl md:text-5xl font-bold mb-6 leading-tight">
            {t('maximizePotential') || "Maximize Your Land's Potential"}
          </h1>
          <p className="text-emerald-100/80 text-lg leading-relaxed mb-8">
            {t('integratedFarmingSubtitle') || 'Integrated farming systems combine crops with animal husbandry to create a self-sustaining ecosystem that increases profit and reduces risk.'}
          </p>
          <div className="flex flex-wrap gap-4">
            <div className="flex items-center gap-2 bg-white/10 px-4 py-2 rounded-xl backdrop-blur-md">
              <TrendingUp className="w-4 h-4 text-emerald-400" />
              <span className="text-sm font-bold">{t('higherProfit') || '30-50% Higher Profit'}</span>
            </div>
            <div className="flex items-center gap-2 bg-white/10 px-4 py-2 rounded-xl backdrop-blur-md">
              <Zap className="w-4 h-4 text-emerald-400" />
              <span className="text-sm font-bold">{t('zeroWaste') || 'Zero Waste System'}</span>
            </div>
          </div>
        </div>
      </header>

      <section className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
        {plans.map((plan, idx) => (
          <motion.div
            key={idx}
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: idx * 0.1 }}
            className={cn(
              "p-8 rounded-[2rem] border transition-all hover:shadow-xl group",
              plan.color,
              plan.borderColor
            )}
          >
            <div className="w-14 h-14 bg-white rounded-2xl flex items-center justify-center shadow-sm mb-6 group-hover:scale-110 transition-transform">
              {plan.icon}
            </div>
            <h3 className="text-2xl font-bold text-gray-900 mb-3">{plan.title}</h3>
            <p className="text-gray-600 text-sm leading-relaxed mb-8">{plan.description}</p>
            
            <div className="space-y-6">
              <div>
                <h4 className="text-xs font-bold text-gray-400 uppercase tracking-widest mb-3">Key Benefits</h4>
                <ul className="space-y-2">
                  {plan.benefits.map((benefit, i) => (
                    <li key={i} className="flex items-start gap-2 text-sm text-gray-700">
                      <CheckCircle2 className="w-4 h-4 text-emerald-500 mt-0.5 shrink-0" />
                      {benefit}
                    </li>
                  ))}
                </ul>
              </div>
              
              <div>
                <h4 className="text-xs font-bold text-gray-400 uppercase tracking-widest mb-3">Getting Started</h4>
                <div className="space-y-3">
                  {plan.steps.map((step, i) => (
                    <div key={i} className="flex items-start gap-3">
                      <div className="w-6 h-6 rounded-full bg-white flex items-center justify-center text-[10px] font-bold text-gray-400 shrink-0 border border-stone-100">
                        {i + 1}
                      </div>
                      <p className="text-sm text-gray-600">{step}</p>
                    </div>
                  ))}
                </div>
              </div>
            </div>

            <button 
              onClick={() => handleDownloadPlan(plan)}
              className="w-full mt-8 py-4 bg-white border border-stone-200 rounded-2xl font-bold text-gray-900 hover:bg-stone-50 transition-all flex items-center justify-center gap-2 group/btn"
             >
              Download Detailed Plan
              <ArrowRight className="w-4 h-4 group-hover/btn:translate-x-1 transition-transform" />
            </button>
          </motion.div>
        ))}
      </section>

      <section className="bg-white p-10 rounded-[2.5rem] border border-stone-200 shadow-sm">
        <div className="flex flex-col md:flex-row gap-10 items-center">
          <div className="flex-1 space-y-6">
            <div className="inline-flex items-center gap-2 px-4 py-2 bg-blue-50 rounded-full text-xs font-bold text-blue-600 uppercase tracking-widest">
              <Info className="w-4 h-4" />
              {t('circularEconomy') || 'The Circular Economy'}
            </div>
            <h2 className="text-3xl font-bold text-gray-900">{t('howCycleWorks') || 'How the Cycle Works'}</h2>
            <p className="text-gray-600 leading-relaxed">
              {t('cycleDesc') || 'In an integrated system, nothing goes to waste. Crop waste becomes animal feed, and animal waste becomes crop fertilizer. This circularity reduces your input costs by up to 40% while doubling your potential revenue streams.'}
            </p>
            <div className="grid grid-cols-2 gap-6">
              <div className="p-4 bg-stone-50 rounded-2xl border border-stone-100">
                <p className="text-2xl font-bold text-emerald-600 mb-1">40%</p>
                <p className="text-xs text-gray-500 font-bold uppercase">{t('costReduction') || 'Cost Reduction'}</p>
              </div>
              <div className="p-4 bg-stone-50 rounded-2xl border border-stone-100">
                <p className="text-2xl font-bold text-blue-600 mb-1">2x</p>
                <p className="text-xs text-gray-500 font-bold uppercase">{t('incomeStreams') || 'Income Streams'}</p>
              </div>
            </div>
          </div>
          <div className="flex-1 w-full max-w-md aspect-square bg-stone-100 rounded-[2rem] relative overflow-hidden flex items-center justify-center p-8">
             <div className="absolute inset-0 opacity-10">
                <Sprout className="w-full h-full text-emerald-900 -rotate-12 translate-x-1/4 translate-y-1/4" />
             </div>
             <div className="relative z-10 text-center space-y-4">
                <div className="w-20 h-20 bg-emerald-600 rounded-3xl flex items-center justify-center mx-auto shadow-xl">
                  <Layers className="w-10 h-10 text-white" />
                </div>
                <p className="font-bold text-gray-900 text-lg">{t('integratedEcosystem') || 'Integrated Ecosystem'}</p>
                <p className="text-sm text-gray-500">{t('integratedEcosystemDesc') || 'Our AI can help you design the perfect balance for your specific land size and soil type.'}</p>
             </div>
          </div>
        </div>
      </section>

      <section className="space-y-8">
        <div className="text-center max-w-2xl mx-auto">
          <h2 className="text-3xl font-bold text-gray-900 mb-4">{t('essentialEquipment') || 'Essential Equipment for Integration'}</h2>
          <p className="text-gray-600">{t('essentialEquipmentDesc') || 'The right tools make managing both crops and livestock significantly easier and more efficient.'}</p>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
          {[
            {
              name: t('powerTiller') || 'Power Tiller',
              desc: t('powerTillerDesc') || 'Versatile tool for land preparation and inter-cultivation in small farms.',
              icon: <Settings className="w-5 h-5 text-emerald-600" />
            },
            {
              name: t('fodderChopper') || 'Fodder Chopper',
              desc: t('fodderChopperDesc') || 'Essential for processing crop residues into digestible feed for livestock.',
              icon: <Wrench className="w-5 h-5 text-blue-600" />
            },
            {
              name: t('milkingMachine') || 'Milking Machine',
              desc: t('milkingMachineDesc') || 'Ensures hygienic milking and reduces labor requirements in dairy farming.',
              icon: <Milk className="w-5 h-5 text-amber-600" />
            },
            {
              name: t('manureSpreader') || 'Manure Spreader',
              desc: t('manureSpreaderDesc') || 'Efficiently distributes animal waste across fields as organic fertilizer.',
              icon: <Hammer className="w-5 h-5 text-orange-600" />
            }
          ].map((item, i) => (
            <div key={i} className="bg-white p-6 rounded-3xl border border-stone-100 shadow-sm hover:shadow-md transition-shadow">
              <div className="w-10 h-10 bg-stone-50 rounded-xl flex items-center justify-center mb-4">
                {item.icon}
              </div>
              <h4 className="font-bold text-gray-900 mb-2">{item.name}</h4>
              <p className="text-xs text-gray-500 leading-relaxed">{item.desc}</p>
            </div>
          ))}
        </div>
      </section>
    </div>
  );
};

export default IntegratedFarming;
