import React, { createContext, useContext, useState, useEffect } from 'react';

export const ALL_LANGUAGES = [
  { code: 'en', name: 'English' },
  { code: 'as', name: 'Assamese (অসমীয়া)' },
  { code: 'bn', name: 'Bengali (বাংলা)' },
  { code: 'brx', name: 'Bodo (बड़ो)' },
  { code: 'doi', name: 'Dogri (डोगरी)' },
  { code: 'gu', name: 'Gujarati (ગુજરાતી)' },
  { code: 'hi', name: 'Hindi (हिन्दी)' },
  { code: 'kn', name: 'Kannada (ಕನ್ನಡ)' },
  { code: 'ks', name: 'Kashmiri (कॉशुर)' },
  { code: 'kok', name: 'Konkani (कोंकणी)' },
  { code: 'mai', name: 'Maithili (मैथिली)' },
  { code: 'ml', name: 'Malayalam (മലയാളം)' },
  { code: 'mni', name: 'Manipuri (মৈতৈলোন্)' },
  { code: 'mr', name: 'Marathi (मराठी)' },
  { code: 'ne', name: 'Nepali (नेपाली)' },
  { code: 'or', name: 'Odia (ଓଡ଼ିଆ)' },
  { code: 'pa', name: 'Punjabi (ਪੰਜਾਬੀ)' },
  { code: 'sa', name: 'Sanskrit (संस्कृतम्)' },
  { code: 'sat', name: 'Santali (ᱥᱟᱱᱛᱟᱲᱤ)' },
  { code: 'sd', name: 'Sindhi (سنڌي)' },
  { code: 'ta', name: 'Tamil (தமிழ்)' },
  { code: 'te', name: 'Telugu (తెలుగు)' },
  { code: 'ur', name: 'Urdu (اردو)' }
];

type Language = string;

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    // Auth
    loginTitle: 'AgroConnect AI',
    loginSubtitle: 'Empowering farmers with AI-driven insights for better yields and sustainable farming.',
    signInWithGoogle: 'Sign in with Google',
    signOut: 'Sign Out',

    // Navigation
    dashboard: 'Dashboard',
    soilHealth: 'Soil Health',
    schemes: 'Schemes',
    marketplace: 'Marketplace',
    aiAssistant: 'AI Assistant',
    diseases: 'Diseases',
    profile: 'Profile',
    reminders: 'Reminders',
    integratedFarming: 'Integrated Farming',
    integratedFarmingSubtitle: 'Integrated farming systems combine crops with animal husbandry to create a self-sustaining ecosystem that increases profit and reduces risk.',
    maximizePotential: "Maximize Your Land's Potential",
    higherProfit: '30-50% Higher Profit',
    zeroWaste: 'Zero Waste System',
    keyBenefits: 'Key Benefits',
    gettingStarted: 'Getting Started',
    downloadPlan: 'Download Detailed Plan',
    circularEconomy: 'The Circular Economy',
    howCycleWorks: 'How the Cycle Works',
    cycleDesc: 'In an integrated system, nothing goes to waste. Crop waste becomes animal feed, and animal waste becomes crop fertilizer. This circularity reduces your input costs by up to 40% while doubling your potential revenue streams.',
    costReduction: 'Cost Reduction',
    incomeStreams: 'Income Streams',
    integratedEcosystem: 'Integrated Ecosystem',
    integratedEcosystemDesc: 'Our AI can help you design the perfect balance for your specific land size and soil type.',
    essentialEquipment: 'Essential Equipment for Integration',
    essentialEquipmentDesc: 'The right tools make managing both crops and livestock significantly easier and more efficient.',
    powerTiller: 'Power Tiller',
    powerTillerDesc: 'Versatile tool for land preparation and inter-cultivation in small farms.',
    fodderChopper: 'Fodder Chopper',
    fodderChopperDesc: 'Essential for processing crop residues into digestible feed for livestock.',
    milkingMachine: 'Milking Machine',
    milkingMachineDesc: 'Ensures hygienic milking and reduces labor requirements in dairy farming.',
    manureSpreader: 'Manure Spreader',
    manureSpreaderDesc: 'Efficiently distributes animal waste across fields as organic fertilizer.',
    cropDairyTitle: 'Crop + Dairy Farming',
    cropDairyDesc: 'The most common and profitable combination for small to medium farmers.',
    cropPoultryTitle: 'Crop + Poultry Farming',
    cropPoultryDesc: 'High-density farming with quick returns and low initial land requirement.',
    cropGoatTitle: 'Crop + Goat/Sheep Farming',
    cropGoatDesc: 'Ideal for drylands and regions with limited water resources.',
    clearSky: 'Clear Sky',
    partlyCloudy: 'Partly Cloudy',
    foggy: 'Foggy',
    rainy: 'Rainy',
    snowy: 'Snowy',
    rainShowers: 'Rain Showers',
    stormy: 'Stormy',
    weatherTitle: 'Live Weather',
    soilHealthTitle: 'Soil Health',
    smartSuggestionsTitle: 'Smart Suggestions',
    marketPricesTitle: 'Market Prices',
    viewMore: 'View More',
    msambDesc: 'Maharashtra State Agriculture Marketing Board.',
    upMandiDesc: 'Uttar Pradesh State Agriculture Marketing Board.',
    karnatakaMandiDesc: 'Karnataka State Agriculture Marketing Board.',
    language: 'Language',

    // Dashboard
    welcome: 'Welcome back',
    dashboardSubtitle: "Welcome to AgroConnect AI. Here's what's happening on your farm today.",
    weather: 'Weather',
    soilHealthSummary: 'Soil Health Summary',
    smartSuggestions: 'Smart Suggestions',
    smartSuggestionsSubtitle: 'Get AI-powered crop recommendations based on your soil and weather.',
    generateSuggestions: 'Generate Suggestions',
    analyzing: 'Analyzing...',
    missingData: 'Please ensure your location and profile are set up.',
    aiResponseGenerated: 'AI suggestions have been generated!',
    reminderAdded: 'Reminder added successfully!',
    close: 'Close',
    watering: 'Watering',
    season: 'Season',
    landsManaged: 'Lands Managed',
    nitrogen: 'Nitrogen (N)',
    phosphorus: 'Phosphorus (P)',
    potassium: 'Potassium (K)',
    phLevel: 'pH Level',
    organicCarbon: 'Organic Carbon',
    lastUpdated: 'Last updated',
    noSoilData: 'No soil data available yet.',
    updateSoilCard: 'Update Soil Card',
    edit: 'Edit',
    markAsSold: 'Mark as Sold',
    updateListing: 'Update Listing',
    actions: 'Actions',
    pricingTip: 'Pricing Accuracy Note: Live prices are sourced from Data.gov.in. For real-time updates, verify your API key in the portal.',
    confirmDelete: 'Confirm Delete',
    deleteListingConfirm: 'Are you sure you want to delete this listing? This action cannot be undone.',
    lastRefreshed: 'Last Refreshed',
    hoursAgo: 'hours ago',
    justNow: 'Just now',

    // Soil Health
    soilHealthSubtitle: 'Monitor and update your soil nutrient levels for better yield.',
    selectLand: 'Select Land',
    defaultLand: 'Default Land',
    enter: 'Enter',
    saving: 'Saving...',
    savedSuccessfully: 'Saved Successfully',
    whyThisMatters: 'Why this matters?',
    soilHealthInfo: 'Regular soil testing helps you apply the right amount of fertilizer, saving money and protecting the environment. Our AI uses these values to suggest the most profitable crops for your specific land.',
    recentTrends: 'Recent Trends',
    labTest: 'Lab Soil Test',
    labTestSubtitle: 'Get a professional lab analysis of your soil for just ₹49.',
    requestLabTest: 'Request Lab Test',
    labTestRequested: 'Lab Test Requested',
    labTestFee: 'Testing Fee: ₹49',
    labTestSteps: 'Our professional will visit your land to collect a soil sample within 48 hours.',
    labTestStatus: 'Test Status',
    pending: 'Pending',
    collected: 'Collected',
    processing: 'Processing',
    completed: 'Completed',
    marketDemand: 'Market Demand',
    upcomingSeason: 'Upcoming Season',
    high: 'High',
    medium: 'Medium',
    low: 'Low',
    plantingInstructions: 'Planting Instructions',
    selectSoilType: 'Select Soil Type (Preset)',
    soilTypeInfo: 'If you don\'t have a soil test report, select your soil type to auto-fill typical nutrient levels.',
    alluvial: 'Alluvial Soil',
    black: 'Black Soil',
    red: 'Red Soil',
    laterite: 'Laterite Soil',
    desert: 'Desert Soil',
    mountain: 'Mountain Soil',
    custom: 'Custom (Manual Entry)',

    // Schemes
    schemesSubtitle: 'Find and apply for national farming schemes you are eligible for.',
    farmer: 'Farmer',
    searchSchemes: 'Search schemes...',
    all: 'All',
    financial: 'Financial',
    insurance: 'Insurance',
    technical: 'Technical',
    eligible: 'Eligible',
    notEligible: 'Not Eligible',
    benefit: 'Benefit',
    category: 'Category',
    remindersSubtitle: 'Set and manage reminders for your farm activities.',
    addReminder: 'Add Reminder',
    fertilizerSuggestions: 'Fertilizer Suggestions',
    aiFertilizerTitle: 'AI Fertilizer Recommendations',
    aiFertilizerSubtitle: 'Based on your soil health and selected crops.',
    getAiSuggestions: 'Get AI Suggestions',
    fertilizerName: 'Fertilizer Name',
    fertilizerQuantity: 'Quantity',
    timing: 'Timing',
    method: 'Method',
    reason: 'Reason',
    noSoilDataForSuggestions: 'Please update your soil health data first to get accurate fertilizer suggestions.',
    reminderTitle: 'Reminder Title',
    reminderDescription: 'Description (Optional)',
    activityType: 'Activity Type',
    dueDate: 'Due Date',
    fertilizer: 'Organic Fertilizer',
    harvesting: 'Harvesting',
    pesticide: 'Pesticide',
    other: 'Other',
    noReminders: 'No reminders set yet.',
    delete: 'Delete',
    markAsDone: 'Mark as Done',
    overdue: 'Overdue',
    dueToday: 'Due Today',
    upcoming: 'Upcoming',
    phoneNumber: 'Phone Number',
    ivrSupport: 'IVR & Voice Support',
    ivrSupportSubtitle: 'Get automated voice assistance and reminders on your phone.',
    callKisanCenter: 'Kisan Call Center (Toll Free)',
    kisanCenterDesc: 'Call for immediate agricultural advice from experts.',
    voiceReminders: 'Voice Reminders',
    voiceRemindersDesc: 'Enable automated calls for your farm reminders. Ensure your phone number is saved above.',
    enabled: 'Enabled',
    disabled: 'Disabled',
    fullName: 'Full Name',
    saveChanges: 'Save Changes',
    profileUpdated: 'Profile Updated',

    // Marketplace
    marketplaceSubtitle: 'Check live mandi prices, trade products, and explore global markets.',
    allStates: 'All States',
    mandiPrices: 'Mandi Prices',
    buyProducts: 'Buy Products',
    myListings: 'My Listings',
    farmEquipment: 'Farm Equipment',
    globalMarkets: 'Global Markets',
    searchMandi: 'Search commodity or market...',
    searchProducts: 'Search products or location...',
    priceTrends: 'Price Trends',
    historicalTrend: 'Historical modal price trend (per quintal)',
    price: 'Price',
    min: 'Min',
    max: 'Max',
    modal: 'Modal',
    perQuintal: 'Per Quintal',
    available: 'Available',
    listedBy: 'Listed by',
    contactSeller: 'Contact Seller',
    contactOwner: 'Contact Owner',
    noProducts: 'No products listed for sale yet.',
    noEquipment: 'No equipment listed yet.',
    listNewProduct: 'List New Product',
    listEquipment: 'List Equipment',
    equipmentName: 'Equipment Name',
    description: 'Description',
    listingType: 'Listing Type',
    forSale: 'For Sale',
    forRent: 'For Rent',
    commodity: 'Commodity',
    quantity: 'Quantity',
    dateListed: 'Date Listed',
    status: 'Status',
    visitPlatform: 'Visit Platform',
    realTimeOpportunities: 'Real-time Opportunities',
    opportunitiesSubtitle: 'Connect with bulk buyers, institutional markets, and export opportunities directly through our partner network.',
    exportMarkets: 'Export Markets',
    bulkBuyers: 'Bulk Buyers',
    joinNetwork: 'Join Network',
    listProduct: 'List Product',
    commodityName: 'Commodity Name',
    unit: 'Unit',
    kilograms: 'Kilograms (kg)',
    quintals: 'Quintals (100kg)',
    tons: 'Tons',
    dozen: 'Dozen',
    pricePerUnit: 'Price per Unit',
    pickupLocation: 'Pickup Location',
    noListings: "You haven't listed any products yet.",
    enamDesc: 'National Agriculture Market (e-NAM) is a pan-India electronic trading portal.',
    agmarknetDesc: 'Agricultural Marketing Information Network for real-time price data.',
    ninjacartDesc: 'India\'s largest fresh produce supply chain platform.',
    dehaatDesc: 'Full-stack agricultural services for farmers.',
    bighaatDesc: 'India\'s leading agri-commerce platform.',

    // AI Assistant
    aiAssistantName: 'Krishi Mitra AI',
    onlineReady: 'Online & Ready to help',
    assistantWelcome: 'Ask me anything about your crops, soil, or government schemes!',
    exampleQ1: 'What crops should I plant in June?',
    exampleQ2: 'How to treat tomato blight?',
    exampleQ3: 'Tell me about PM-KISAN scheme.',
    typeQuestion: 'Type your question here...',

    // Diseases & Pests
    diseasesAndPests: 'Diseases & Pests',
    pests: 'Pests',
    diseasesSubtitle: 'Identify crop issues and get expert treatment suggestions.',
    aiDiagnosis: 'AI Diagnosis',
    pestIdentification: 'Pest Identification',
    pestSigns: 'Pest Signs / Symptoms',
    pestPlaceholder: 'e.g. holes in leaves, small green insects',
    identifyNow: 'Identify Now',
    cropName: 'Crop Name',
    cropPlaceholder: 'e.g. Tomato, Wheat',
    uploadPhoto: 'Upload Photo',
    clickToUpload: 'Click to upload photo',
    symptomsOptional: 'Symptoms (optional)',
    symptomsPlaceholder: 'e.g. yellow spots, wilting',
    diagnoseNow: 'Diagnose Now',
    diagnosisResult: 'Diagnosis Result',
    pestResult: 'Pest Identified',
    confidence: 'Confidence',
    disease: 'Disease',
    pestName: 'Pest Name',
    identification: 'Identification',
    cause: 'Cause',
    immediateRemedy: 'Immediate Remedy',
    ecoFriendlyControl: 'Eco-friendly Control',
    prevention: 'Prevention',
    similarDiseases: 'Similar Diseases',
    addToCropDiary: 'Add to My Crop Diary',
    addToPestLog: 'Add to Pest Log',
    viewInDatabase: 'View in Database',
    clearResults: 'Clear Results',
    scientificName: 'Scientific Name',
    pathology: 'Pathology',
    treatments: 'Treatments',
    lifeCycle: 'Life Cycle',
    chemicalControl: 'Chemical Control',
    localizedRecommendations: 'Localized Recommendations',
    multipleImagesHint: 'You can upload up to 3 images for better accuracy.',
    searchDiseaseDatabase: 'Search disease database...',
    searchPestDatabase: 'Search pest database...',
    pestDatabaseComingSoon: 'Pest Database Coming Soon',
    pestDatabaseDesc: 'We are currently building a comprehensive database of common agricultural pests. Use the AI Diagnosis tool for immediate help!',
    trending: 'Trending',
    symptoms: 'Symptoms',
    viewFullRemedy: 'View Full Remedy',

    // Profile
    farmerProfile: 'Farmer Profile',
    profileSubtitle: 'Manage your personal information and multiple farm locations.',
    personalInfo: 'Personal Information',
    farmerCategory: 'Farmer Category',
    smallFarmer: 'Small Farmer',
    marginalFarmer: 'Marginal Farmer',
    largeFarmer: 'Large Farmer',
    aadharLinked: 'Aadhar Linked',
    aadharRequired: 'Required for most government schemes',
    myLands: 'My Lands',
    acres: 'Acres',
    noLands: 'No lands added yet.',
    addNewLand: 'Add New Land',
    landName: 'Land Name / Identifier',
    landNamePlaceholder: 'e.g. North Field, Village Farm',
    locationAddress: 'Location Address',
    soilType: 'Soil Type',
    soilTypePlaceholder: 'e.g. Black',
    sizeAcres: 'Size (Acres)',
    addLand: 'Add Land',
    landStatus: 'Land Status',
    planted: 'Planted',
    empty: 'Empty',
    currentCrop: 'Current Crop',
    enterCurrentCrop: 'Search or enter current crop...',

    // General
    ivrAssistant: 'IVR Assistant',
    location: 'Location',
    date: 'Date',
    sold: 'Sold',
    selectLocationOnMap: 'Select Location on Map',
    confirmLocation: 'Confirm Location',
    currentLocation: 'Current Location',
    latitude: 'Latitude',
    longitude: 'Longitude',
  },
  hi: {
    // Auth
    loginTitle: 'AgroConnect AI',
    loginSubtitle: 'बेहतर पैदावार और टिकाऊ खेती के लिए AI-संचालित अंतर्दृष्टि के साथ किसानों को सशक्त बनाना।',
    signInWithGoogle: 'Google के साथ साइन इन करें',
    signOut: 'साइन आउट',

    // Navigation
    dashboard: 'डैशबोर्ड',
    soilHealth: 'मिट्टी का स्वास्थ्य',
    schemes: 'योजनाएं',
    marketplace: 'बाज़ार',
    aiAssistant: 'AI सहायक',
    diseases: 'रोग',
    profile: 'प्रोफ़ाइल',
    reminders: 'अनुस्मारक',
    integratedFarming: 'एकीकृत खेती',
    integratedFarmingSubtitle: 'एकीकृत कृषि प्रणालियाँ लाभ बढ़ाने और जोखिम कम करने के लिए एक आत्मनिर्भर पारिस्थितिकी तंत्र बनाने के लिए पशुपालन के साथ फसलों को जोड़ती हैं।',
    maximizePotential: 'अपनी भूमि की क्षमता को अधिकतम करें',
    higherProfit: '30-50% अधिक लाभ',
    zeroWaste: 'जीरो वेस्ट सिस्टम',
    keyBenefits: 'मुख्य लाभ',
    gettingStarted: 'शुरू करना',
    downloadPlan: 'विस्तृत योजना डाउनलोड करें',
    circularEconomy: 'चक्रीय अर्थव्यवस्था',
    howCycleWorks: 'चक्र कैसे काम करता है',
    cycleDesc: 'एक एकीकृत प्रणाली में, कुछ भी बेकार नहीं जाता है। फसल का कचरा पशु आहार बन जाता है, और पशु अपशिष्ट फसल उर्वरक बन जाता है। यह चक्रीयता आपकी इनपुट लागत को 40% तक कम कर देती है जबकि आपकी संभावित राजस्व धाराओं को दोगुना कर देती है।',
    costReduction: 'लागत में कमी',
    incomeStreams: 'आय के स्रोत',
    integratedEcosystem: 'एकीकृत पारिस्थितिकी तंत्र',
    integratedEcosystemDesc: 'हमारा AI आपको आपके विशिष्ट भूमि आकार और मिट्टी के प्रकार के लिए सही संतुलन डिजाइन करने में मदद कर सकता है।',
    essentialEquipment: 'एकीकरण के लिए आवश्यक उपकरण',
    essentialEquipmentDesc: 'सही उपकरण फसलों और पशुधन दोनों के प्रबंधन को काफी आसान और अधिक कुशल बनाते हैं।',
    powerTiller: 'पावर टिलर',
    powerTillerDesc: 'छोटे खेतों में भूमि तैयार करने और अंतर-खेती के लिए बहुमुखी उपकरण।',
    fodderChopper: 'चारा काटने की मशीन',
    fodderChopperDesc: 'पशुधन के लिए फसल अवशेषों को सुपाच्य चारे में संसाधित करने के लिए आवश्यक।',
    milkingMachine: 'दुहने की मशीन',
    milkingMachineDesc: 'डेयरी फार्मिंग में स्वच्छ दूध दुहना सुनिश्चित करता है और श्रम आवश्यकताओं को कम करता है।',
    manureSpreader: 'खाद फैलाने वाला',
    manureSpreaderDesc: 'जैविक उर्वरक के रूप में खेतों में पशु अपशिष्ट को कुशलतापूर्वक वितरित करता है।',
    cropDairyTitle: 'फसल + डेयरी फार्मिंग',
    cropDairyDesc: 'छोटे से मध्यम किसानों के लिए सबसे आम और लाभदायक संयोजन।',
    cropPoultryTitle: 'फसल + पोल्ट्री फार्मिंग',
    cropPoultryDesc: 'त्वरित रिटर्न और कम प्रारंभिक भूमि आवश्यकता के साथ उच्च घनत्व वाली खेती।',
    cropGoatTitle: 'फसल + बकरी/भेड़ पालन',
    cropGoatDesc: 'शुष्क भूमि और सीमित जल संसाधनों वाले क्षेत्रों के लिए आदर्श।',
    clearSky: 'साफ आकाश',
    partlyCloudy: 'आंशिक रूप से बादल छाए रहेंगे',
    foggy: 'धुंधला',
    rainy: 'बरसात',
    snowy: 'बर्फीला',
    rainShowers: 'बारिश की बौछारें',
    stormy: 'तूफानी',
    weatherTitle: 'लाइव मौसम',
    soilHealthTitle: 'मिट्टी का स्वास्थ्य',
    smartSuggestionsTitle: 'स्मार्ट सुझाव',
    marketPricesTitle: 'बाजार भाव',
    viewMore: 'और देखें',
    msambDesc: 'महाराष्ट्र राज्य कृषि विपणन बोर्ड।',
    upMandiDesc: 'उत्तर प्रदेश राज्य कृषि विपणन बोर्ड।',
    karnatakaMandiDesc: 'कर्नाटक राज्य कृषि विपणन बोर्ड।',
    language: 'भाषा',

    // Dashboard
    welcome: 'स्वागत है',
    dashboardSubtitle: "AgroConnect AI में आपका स्वागत है। आज आपके खेत में क्या हो रहा है, यहाँ देखें।",
    weather: 'मौसम',
    soilHealthSummary: 'मिट्टी स्वास्थ्य सारांश',
    smartSuggestions: 'स्मार्ट सुझाव',
    smartSuggestionsSubtitle: 'अपनी मिट्टी और मौसम के आधार पर AI-संचालित फसल सिफारिशें प्राप्त करें।',
    generateSuggestions: 'सुझाव उत्पन्न करें',
    analyzing: 'विश्लेषण कर रहा है...',
    missingData: 'कृपया सुनिश्चित करें कि आपका स्थान और प्रोफ़ाइल सेटअप है।',
    aiResponseGenerated: 'एआई सुझाव तैयार हो गए हैं!',
    reminderAdded: 'रिमाइंडर सफलतापूर्वक जोड़ दिया गया!',
    close: 'बंद करें',
    watering: 'सिंचाई',
    season: 'सीजन',
    landsManaged: 'प्रबंधित भूमि',
    nitrogen: 'नाइट्रोजन (N)',
    phosphorus: 'फास्फोरस (P)',
    potassium: 'पोटेशियम (K)',
    phLevel: 'pH स्तर',
    organicCarbon: 'जैविक कार्बन',
    lastUpdated: 'अंतिम अपडेट',
    noSoilData: 'अभी तक कोई मिट्टी डेटा उपलब्ध नहीं है।',
    updateSoilCard: 'मिट्टी कार्ड अपडेट करें',
    edit: 'संपादित करें',
    markAsSold: 'बिका हुआ चिह्नित करें',
    updateListing: 'लिस्टिंग अपडेट करें',
    actions: 'कार्रवाई',
    pricingTip: 'मूल्य निर्धारण सटीकता नोट: लाइव कीमतें data.gov.in से ली गई हैं। वास्तविक समय के अपडेट के लिए, पोर्टल में अपनी एपीआई कुंजी सत्यापित करें।',
    confirmDelete: 'हटाने की पुष्टि करें',
    deleteListingConfirm: 'क्या आप वाकई इस लिस्टिंग को हटाना चाहते हैं? यह कार्रवाई पूर्ववत नहीं की जा सकती।',
    lastRefreshed: 'पिछली बार रिफ्रेश किया गया',
    hoursAgo: 'घंटे पहले',
    justNow: 'अभी-अभी',

    // Soil Health
    soilHealthSubtitle: 'बेहतर उपज के लिए अपनी मिट्टी के पोषक तत्वों के स्तर की निगरानी और अपडेट करें।',
    selectLand: 'भूमि चुनें',
    defaultLand: 'डिफ़ॉल्ट भूमि',
    enter: 'दर्ज करें',
    saving: 'सहेज रहा है...',
    savedSuccessfully: 'सफलतापूर्वक सहेजा गया',
    whyThisMatters: 'यह क्यों मायने रखता है?',
    soilHealthInfo: 'नियमित मिट्टी परीक्षण आपको उर्वरक की सही मात्रा का उपयोग करने में मदद करता है, जिससे पैसे की बचत होती है और पर्यावरण की रक्षा होती है। हमारा AI आपकी विशिष्ट भूमि के लिए सबसे अधिक लाभदायक फसलों का सुझाव देने के लिए इन मूल्यों का उपयोग करता है।',
    recentTrends: 'हाल के रुझान',
    labTest: 'लैब मिट्टी परीक्षण',
    labTestSubtitle: 'सिर्फ ₹49 में अपनी मिट्टी का पेशेवर लैब विश्लेषण प्राप्त करें।',
    requestLabTest: 'लैब परीक्षण का अनुरोध करें',
    labTestRequested: 'लैब परीक्षण का अनुरोध किया गया',
    labTestFee: 'परीक्षण शुल्क: ₹49',
    labTestSteps: 'हमारा पेशेवर 48 घंटों के भीतर मिट्टी का नमूना एकत्र करने के लिए आपकी भूमि पर आएगा।',
    labTestStatus: 'परीक्षण की स्थिति',
    pending: 'लंबित',
    collected: 'एकत्रित',
    processing: 'प्रसंस्करण',
    completed: 'पूरा हुआ',
    marketDemand: 'बाजार की मांग',
    upcomingSeason: 'आगामी सीजन',
    high: 'उच्च',
    medium: 'मध्यम',
    low: 'कम',
    plantingInstructions: 'रोपण निर्देश',
    selectSoilType: 'मिट्टी का प्रकार चुनें (प्रीसेट)',
    soilTypeInfo: 'यदि आपके पास मिट्टी परीक्षण रिपोर्ट नहीं है, तो विशिष्ट पोषक तत्व स्तरों को ऑटो-फिल करने के लिए अपनी मिट्टी का प्रकार चुनें।',
    alluvial: 'जलोढ़ मिट्टी',
    black: 'काली मिट्टी',
    red: 'लाल मिट्टी',
    laterite: 'लैटेराइट मिट्टी',
    desert: 'रेतीली मिट्टी',
    mountain: 'पहाड़ी मिट्टी',
    custom: 'कस्टम (मैनुअल प्रविष्टि)',

    // Schemes
    schemesSubtitle: 'उन राष्ट्रीय कृषि योजनाओं को खोजें और आवेदन करें जिनके लिए आप पात्र हैं।',
    farmer: 'किसान',
    searchSchemes: 'योजनाएं खोजें...',
    all: 'सभी',
    financial: 'वित्तीय',
    insurance: 'बीमा',
    technical: 'तकनीकी',
    eligible: 'पात्र',
    notEligible: 'पात्र नहीं',
    benefit: 'लाभ',
    category: 'श्रेणी',
    remindersSubtitle: 'अपनी कृषि गतिविधियों के लिए अनुस्मारक सेट करें और प्रबंधित करें।',
    addReminder: 'अनुस्मारक जोड़ें',
    fertilizerSuggestions: 'उर्वरक सुझाव',
    aiFertilizerTitle: 'AI उर्वरक सिफारिशें',
    aiFertilizerSubtitle: 'आपकी मिट्टी के स्वास्थ्य और चयनित फसलों के आधार पर।',
    getAiSuggestions: 'AI सुझाव प्राप्त करें',
    fertilizerName: 'उर्वरक का नाम',
    fertilizerQuantity: 'मात्रा',
    timing: 'समय',
    method: 'विधि',
    reason: 'कारण',
    noSoilDataForSuggestions: 'सटीक उर्वरक सुझाव प्राप्त करने के लिए कृपया पहले अपनी मिट्टी के स्वास्थ्य डेटा को अपडेट करें।',
    reminderTitle: 'अनुस्मारक शीर्षक',
    reminderDescription: 'विवरण (वैकल्पिक)',
    activityType: 'गतिविधि का प्रकार',
    dueDate: 'नियत तारीख',
    fertilizer: 'जैविक उर्वरक',
    harvesting: 'कटाई',
    pesticide: 'कीटनाशक',
    other: 'अन्य',
    noReminders: 'अभी तक कोई अनुस्मारक सेट नहीं किया गया है।',
    delete: 'हटाएं',
    markAsDone: 'पूरा चिह्नित करें',
    overdue: 'विलंबित',
    dueToday: 'आज देय',
    upcoming: 'आगामी',
    phoneNumber: 'फ़ोन नंबर',
    ivrSupport: 'IVR और वॉयस सपोर्ट',
    ivrSupportSubtitle: 'अपने फ़ोन पर स्वचालित वॉयस सहायता और अनुस्मारक प्राप्त करें।',
    callKisanCenter: 'किसान कॉल सेंटर (टोल फ्री)',
    kisanCenterDesc: 'विशेषज्ञों से तत्काल कृषि सलाह के लिए कॉल करें।',
    voiceReminders: 'वॉयस अनुस्मारक',
    voiceRemindersDesc: 'अपने कृषि अनुस्मारक के लिए स्वचालित कॉल सक्षम करें। सुनिश्चित करें कि आपका फ़ोन नंबर ऊपर सहेजा गया है।',
    enabled: 'सक्षम',
    disabled: 'अक्षम',
    fullName: 'पूरा नाम',
    saveChanges: 'परिवर्तन सहेजें',
    profileUpdated: 'प्रोफ़ाइल अपडेट की गई',

    // Marketplace
    marketplaceSubtitle: 'लाइव मंडी भाव देखें, उत्पादों का व्यापार करें और वैश्विक बाजारों का पता लगाएं।',
    allStates: 'सभी राज्य',
    mandiPrices: 'मंडी भाव',
    buyProducts: 'उत्पाद खरीदें',
    myListings: 'मेरी लिस्टिंग',
    globalMarkets: 'वैश्विक बाजार',
    searchMandi: 'वस्तु या मंडी खोजें...',
    searchProducts: 'उत्पाद या स्थान खोजें...',
    priceTrends: 'मूल्य रुझान',
    historicalTrend: 'ऐतिहासिक मॉडल मूल्य रुझान (प्रति क्विंटल)',
    price: 'कीमत',
    min: 'न्यूनतम',
    max: 'अधिकतम',
    modal: 'मॉडल',
    perQuintal: 'प्रति क्विंटल',
    available: 'उपलब्ध',
    listedBy: 'द्वारा सूचीबद्ध',
    contactSeller: 'विक्रेता से संपर्क करें',
    noProducts: 'बिक्री के लिए अभी तक कोई उत्पाद सूचीबद्ध नहीं है।',
    listNewProduct: 'नया उत्पाद सूचीबद्ध करें',
    commodity: 'वस्तु',
    quantity: 'मात्रा',
    dateListed: 'सूचीबद्ध तिथि',
    status: 'स्थिति',
    visitPlatform: 'प्लेटफ़ॉर्म पर जाएँ',
    realTimeOpportunities: 'वास्तविक समय के अवसर',
    opportunitiesSubtitle: 'हमारे पार्टनर नेटवर्क के माध्यम से सीधे थोक खरीदारों, संस्थागत बाजारों और निर्यात के अवसरों से जुड़ें।',
    exportMarkets: 'निर्यात बाजार',
    bulkBuyers: 'थोक खरीदार',
    joinNetwork: 'नेटवर्क में शामिल हों',
    listProduct: 'उत्पाद सूचीबद्ध करें',
    commodityName: 'वस्तु का नाम',
    unit: 'इकाई',
    kilograms: 'किलोग्राम (kg)',
    quintals: 'क्विंटल (100kg)',
    tons: 'टन',
    dozen: 'दर्जन',
    pricePerUnit: 'प्रति इकाई मूल्य',
    pickupLocation: 'पिकअप स्थान',
    noListings: "आपने अभी तक कोई उत्पाद सूचीबद्ध नहीं किया है।",
    enamDesc: 'राष्ट्रीय कृषि बाजार (e-NAM) एक अखिल भारतीय इलेक्ट्रॉनिक ट्रेडिंग पोर्टल है।',
    agmarknetDesc: 'वास्तविक समय मूल्य डेटा के लिए कृषि विपणन सूचना नेटवर्क।',
    ninjacartDesc: 'भारत का सबसे बड़ा ताजा उपज आपूर्ति श्रृंखला मंच।',
    dehaatDesc: 'किसानों के लिए पूर्ण-स्टैक कृषि सेवाएं।',
    bighaatDesc: 'भारत का प्रमुख कृषि-वाणिज्य मंच।',

    // AI Assistant
    aiAssistantName: 'कृषि मित्र AI',
    onlineReady: 'ऑनलाइन और मदद के लिए तैयार',
    assistantWelcome: 'मुझसे अपनी फसलों, मिट्टी या सरकारी योजनाओं के बारे में कुछ भी पूछें!',
    exampleQ1: 'मुझे जून में कौन सी फसलें लगानी चाहिए?',
    exampleQ2: 'टमाटर के झुलसा रोग का इलाज कैसे करें?',
    exampleQ3: 'पीएम-किसान योजना के बारे में बताएं।',
    typeQuestion: 'अपना प्रश्न यहाँ टाइप करें...',

    // Diseases & Pests
    diseasesAndPests: 'रोग और कीट',
    pests: 'कीट',
    diseasesSubtitle: 'फसल की समस्याओं की पहचान करें और विशेषज्ञ उपचार सुझाव प्राप्त करें।',
    aiDiagnosis: 'AI निदान',
    pestIdentification: 'कीट पहचान',
    pestSigns: 'कीट के लक्षण / संकेत',
    pestPlaceholder: 'जैसे पत्तियों में छेद, छोटे हरे कीड़े',
    identifyNow: 'अभी पहचानें',
    cropName: 'फसल का नाम',
    cropPlaceholder: 'जैसे टमाटर, गेहूं',
    uploadPhoto: 'फोटो अपलोड करें',
    clickToUpload: 'फोटो अपलोड करने के लिए क्लिक करें',
    symptomsOptional: 'लक्षण (वैकल्पिक)',
    symptomsPlaceholder: 'जैसे पीले धब्बे, मुरझाना',
    diagnoseNow: 'अभी निदान करें',
    diagnosisResult: 'निदान परिणाम',
    pestResult: 'कीट की पहचान हुई',
    confidence: 'आत्मविश्वास',
    disease: 'रोग',
    pestName: 'कीट का नाम',
    identification: 'पहचान',
    cause: 'कारण',
    immediateRemedy: 'तत्काल उपाय',
    ecoFriendlyControl: 'पर्यावरण के अनुकूल नियंत्रण',
    prevention: 'रोकथाम',
    similarDiseases: 'समान रोग',
    addToCropDiary: 'मेरी फसल डायरी में जोड़ें',
    addToPestLog: 'कीट लॉग में जोड़ें',
    viewInDatabase: 'डेटाबेस में देखें',
    clearResults: 'परिणाम साफ़ करें',
    scientificName: 'वैज्ञानिक नाम',
    pathology: 'रोग-विज्ञान',
    treatments: 'उपचार',
    lifeCycle: 'जीवन चक्र',
    chemicalControl: 'रासायनिक नियंत्रण',
    localizedRecommendations: 'स्थानीय सिफारिशें',
    multipleImagesHint: 'बेहतर सटीकता के लिए आप 3 फोटो तक अपलोड कर सकते हैं।',
    searchDiseaseDatabase: 'रोग डेटाबेस खोजें...',
    searchPestDatabase: 'कीट डेटाबेस खोजें...',
    pestDatabaseComingSoon: 'कीट डेटाबेस जल्द ही आ रहा है',
    pestDatabaseDesc: 'हम वर्तमान में सामान्य कृषि कीटों का एक व्यापक डेटाबेस बना रहे हैं। तत्काल सहायता के लिए एआई निदान उपकरण का उपयोग करें!',
    trending: 'ट्रेंडिंग',
    symptoms: 'लक्षण',
    viewFullRemedy: 'पूरा उपाय देखें',

    // Profile
    farmerProfile: 'किसान प्रोफ़ाइल',
    profileSubtitle: 'अपनी व्यक्तिगत जानकारी और कई कृषि स्थानों का प्रबंधन करें।',
    personalInfo: 'व्यक्तिगत जानकारी',
    farmerCategory: 'किसान श्रेणी',
    smallFarmer: 'छोटा किसान',
    marginalFarmer: 'सीमांत किसान',
    largeFarmer: 'बड़ा किसान',
    aadharLinked: 'आधार लिंक है',
    aadharRequired: 'अधिकांश सरकारी योजनाओं के लिए आवश्यक',
    myLands: 'मेरी भूमि',
    acres: 'एकड़',
    noLands: 'अभी तक कोई भूमि नहीं जोड़ी गई है।',
    addNewLand: 'नई भूमि जोड़ें',
    landName: 'भूमि का नाम / पहचानकर्ता',
    landNamePlaceholder: 'जैसे उत्तर क्षेत्र, गांव का खेत',
    locationAddress: 'स्थान का पता',
    soilType: 'मिट्टी का प्रकार',
    soilTypePlaceholder: 'जैसे काली मिट्टी',
    sizeAcres: 'आकार (एकड़)',
    addLand: 'भूमि जोड़ें',
    landStatus: 'ज़मीन की स्थिति',
    planted: 'बुवाई हो चुकी',
    empty: 'खाली',
    currentCrop: 'वर्तमान फसल',
    enterCurrentCrop: 'वर्तमान फसल दर्ज करें...',

    // General
    ivrAssistant: 'IVR सहायक',
    location: 'स्थान',
    date: 'तारीख',
    sold: 'बिका हुआ',
    selectLocationOnMap: 'मानचित्र पर स्थान चुनें',
    confirmLocation: 'स्थान की पुष्टि करें',
    currentLocation: 'वर्तमान स्थान',
    latitude: 'अक्षांश',
    longitude: 'देशांतर',
  },
  mr: {
    // Auth
    loginTitle: 'AgroConnect AI',
    loginSubtitle: 'शाश्वत भविष्यासाठी स्मार्ट शेती उपाय.',
    signInWithGoogle: 'Google सह साइन इन करा',
    signOut: 'साइन आउट',

    // Navigation
    dashboard: 'डॅशबोर्ड',
    soilHealth: 'मातीचे आरोग्य',
    schemes: 'योजना',
    marketplace: 'बाजारपेठ',
    aiAssistant: 'AI सहाय्यक',
    diseases: 'रोग',
    profile: 'प्रोफाइल',
    reminders: 'स्मरणपत्र',
    integratedFarming: 'एकात्मिक शेती',
    integratedFarmingSubtitle: 'एकात्मिक शेती पद्धती नफा वाढवण्यासाठी आणि जोखीम कमी करण्यासाठी स्वयंपूर्ण परिसंस्था तयार करण्यासाठी पशुपालनासह पिकांची जोड देतात.',
    maximizePotential: 'तुमच्या जमिनीची क्षमता वाढवा',
    higherProfit: '30-50% जास्त नफा',
    zeroWaste: 'झिरो वेस्ट सिस्टम',
    keyBenefits: 'मुख्य फायदे',
    gettingStarted: 'सुरुवात करणे',
    downloadPlan: 'तपशीलवार योजना डाउनलोड करा',
    circularEconomy: 'चक्रीय अर्थव्यवस्था',
    howCycleWorks: 'चक्र कसे कार्य करते',
    cycleDesc: 'एकात्मिक प्रणालीमध्ये, काहीही वाया जात नाही. पिकांचा कचरा पशुखाद्य बनतो आणि प्राण्यांचा कचरा पिकांचे खत बनतो. ही चक्रीयता तुमच्या इनपुट खर्चात 40% पर्यंत घट करते आणि तुमच्या संभाव्य महसूल प्रवाहात दुप्पट वाढ करते.',
    costReduction: 'खर्च कपात',
    incomeStreams: 'उत्पन्नाचे स्रोत',
    integratedEcosystem: 'एकात्मिक परिसंस्था',
    integratedEcosystemDesc: 'आमचे AI तुम्हाला तुमच्या विशिष्ट जमिनीच्या आकारासाठी आणि मातीच्या प्रकारासाठी योग्य संतुलन डिझाइन करण्यात मदत करू शकते.',
    essentialEquipment: 'एकात्मिकरणासाठी आवश्यक उपकरणे',
    essentialEquipmentDesc: 'योग्य साधने पिके आणि पशुधन दोन्हीचे व्यवस्थापन लक्षणीयरीत्या सोपे आणि अधिक कार्यक्षम करतात.',
    powerTiller: 'पॉवर टिलर',
    powerTillerDesc: 'लहान शेतात जमीन तयार करण्यासाठी आणि आंतर-मशागतीसाठी अष्टपैलू साधन.',
    fodderChopper: 'चारा कापण्याचे यंत्र',
    fodderChopperDesc: 'पशुधनासाठी पिकांच्या अवशेषांवर प्रक्रिया करून पचण्याजोगे खाद्य तयार करण्यासाठी आवश्यक.',
    milkingMachine: 'दूध काढण्याचे यंत्र',
    milkingMachineDesc: 'डेअरी फार्मिंगमध्ये स्वच्छ दूध काढणे सुनिश्चित करते आणि श्रमाची आवश्यकता कमी करते.',
    manureSpreader: 'खत पसरवणारे यंत्र',
    manureSpreaderDesc: 'सेंद्रिय खत म्हणून शेतात प्राण्यांच्या कचऱ्याचे कार्यक्षमतेने वाटप करते.',
    cropDairyTitle: 'पीक + दुग्धव्यवसाय',
    cropDairyDesc: 'लहान ते मध्यम शेतकऱ्यांसाठी सर्वात सामान्य आणि फायदेशीर संयोजन.',
    cropPoultryTitle: 'पीक + कुक्कुटपालन',
    cropPoultryDesc: 'त्वरीत परतावा आणि कमी प्रारंभिक जमिनीच्या आवश्यकतेसह उच्च-घनता शेती.',
    cropGoatTitle: 'पीक + शेळी/मेंढी पालन',
    cropGoatDesc: 'कोरडवाहू जमीन आणि मर्यादित पाणी संसाधने असलेल्या क्षेत्रांसाठी आदर्श.',
    clearSky: 'स्वच्छ आकाश',
    partlyCloudy: 'अंशतः ढगाळ',
    foggy: 'धुके',
    rainy: 'पावसाळी',
    snowy: 'बर्फाच्छादित',
    rainShowers: 'पावसाच्या सरी',
    stormy: 'वादळी',
    weatherTitle: 'थेट हवामान',
    soilHealthTitle: 'मातीचे आरोग्य',
    smartSuggestionsTitle: 'स्मार्ट सूचना',
    marketPricesTitle: 'बाजार भाव',
    viewMore: 'अधिक पहा',
    msambDesc: 'महाराष्ट्र राज्य कृषी पणन मंडळ.',
    upMandiDesc: 'उत्तर प्रदेश राज्य कृषी पणन मंडळ.',
    karnatakaMandiDesc: 'कर्नाटक राज्य कृषी पणन मंडळ.',
    language: 'भाषा',

    // Dashboard
    welcome: 'स्वागत आहे',
    dashboardSubtitle: 'एग्रो-कनेक्ट एआई मध्ये आपले स्वागत आहे. आज तुमच्या शेतात काय घडत आहे ते येथे आहे.',
    weather: 'हवामान',
    soilHealthSummary: 'माती आरोग्य सारांश',
    smartSuggestions: 'स्मार्ट सूचना',
    smartSuggestionsSubtitle: 'तुमच्या माती आणि हवामानावर आधारित AI-आधारित पीक शिफारसी मिळवा.',
    generateSuggestions: 'सूचना तयार करा',
    analyzing: 'विश्लेषण करत आहे...',
    missingData: 'कृपया खात्री करा की तुमचे स्थान आणि प्रोफाइल सेट केले आहे.',
    aiResponseGenerated: 'एआई सूचना तयार झाली आहे!',
    reminderAdded: 'स्मरणपत्र यशस्वीरित्या जोडले गेले!',
    close: 'बंद करा',
    watering: 'पाणी व्यवस्थापन',
    season: 'हंगाम',
    landsManaged: 'व्यवस्थापित जमिनी',
    nitrogen: 'नायट्रोजन (N)',
    phosphorus: 'फॉस्फरस (P)',
    potassium: 'पोटॅशियम (K)',
    phLevel: 'पीएच पातळी',
    organicCarbon: 'सेंद्रिय कर्ब',
    lastUpdated: 'शेवटचे अपडेट',
    noSoilData: 'अद्याप मातीचा डेटा उपलब्ध नाही.',
    updateSoilCard: 'माती कार्ड अपडेट करा',
    edit: 'संपादित करा',
    markAsSold: 'विकले म्हणून चिन्हांकित करा',
    updateListing: 'सूची अपडेट करा',
    actions: 'कृती',
    pricingTip: 'किंमत अचूकता टीप: थेट किमती data.gov.in कडून मिळवल्या जातात. रिअल-टाइम अपडेटसाठी, पोर्टलमध्ये तुमची एपीआई की सत्यापित करा.',
    confirmDelete: 'डिलीट करण्याची खात्री करा',
    deleteListingConfirm: 'तुम्हाला खात्री आहे की तुम्ही ही लिस्टिंग हटवू इच्छिता? ही कृती पूर्ववत केली जाऊ शकत नाही.',
    lastRefreshed: 'शेवटचे रिफ्रेश',
    hoursAgo: 'तासापूर्वी',
    justNow: 'काही वेळापूर्वी',

    // Soil Health
    soilHealthSubtitle: 'चांगल्या उत्पादनासाठी तुमच्या मातीतील पोषक तत्वांच्या पातळीवर लक्ष ठेवा आणि अपडेट करा.',
    selectLand: 'जमीन निवडा',
    defaultLand: 'डीफॉल्ट जमीन',
    enter: 'दाखल करा',
    saving: 'जतन करत आहे...',
    savedSuccessfully: 'यशस्वीरित्या जतन केले',
    whyThisMatters: 'हे का महत्त्वाचे आहे?',
    soilHealthInfo: 'नियमित माती परीक्षण तुम्हाला योग्य प्रमाणात खत वापरण्यास मदत करते, पैसे वाचवते आणि पर्यावरणाचे रक्षण करते. आमचे AI या मूल्यांचा वापर करून तुमच्या विशिष्ट जमिनीसाठी सर्वात फायदेशीर पिकांची शिफारस करते.',
    recentTrends: 'अलीकडील कल',
    labTest: 'लॅब माती परीक्षण',
    labTestSubtitle: 'फक्त ₹49 मध्ये तुमच्या मातीचे व्यावसायिक लॅब विश्लेषण मिळवा.',
    requestLabTest: 'लॅब चाचणीसाठी विनंती करा',
    labTestRequested: 'लॅब चाचणीची विनंती केली',
    labTestFee: 'चाचणी शुल्क: ₹49',
    labTestSteps: 'आमचा व्यावसायिक ४८ तासांच्या आत मातीचा नमुना गोळा करण्यासाठी तुमच्या जमिनीवर येईल.',
    labTestStatus: 'चाचणी स्थिती',
    pending: 'प्रलंबित',
    collected: 'गोळा केले',
    processing: 'प्रक्रिया सुरू',
    completed: 'पूर्ण झाले',
    marketDemand: 'बाजारातील मागणी',
    upcomingSeason: 'येणारा हंगाम',
    high: 'उच्च',
    medium: 'मध्यम',
    low: 'कमी',
    plantingInstructions: 'लागवडीच्या सूचना',
    selectSoilType: 'मातीचा प्रकार निवडा (प्रीसेट)',
    soilTypeInfo: 'तुमच्याकडे माती परीक्षण अहवाल नसल्यास, विशिष्ट पोषक पातळी ऑटो-फिल करण्यासाठी तुमचा मातीचा प्रकार निवडा.',
    alluvial: 'गाळाची माती',
    black: 'काळी माती',
    red: 'लाल माती',
    laterite: 'लॅटेराइट माती',
    desert: 'वाळवंटी माती',
    mountain: 'डोंगराळ माती',
    custom: 'सानुकूल (मॅन्युअल एंट्री)',

    // Schemes
    schemesSubtitle: 'तुम्ही पात्र असलेल्या राष्ट्रीय शेती योजना शोधा आणि अर्ज करा.',
    farmer: 'शेतकरी',
    searchSchemes: 'योजना शोधा...',
    all: 'सर्व',
    financial: 'आर्थिक',
    insurance: 'विमा',
    technical: 'तांत्रिक',
    eligible: 'पात्र',
    notEligible: 'पात्र नाही',
    benefit: 'लाभ',
    category: 'वर्ग',
    remindersSubtitle: 'तुमच्या शेती उपक्रमांसाठी स्मरणपत्रे सेट करा आणि व्यवस्थापित करा.',
    addReminder: 'स्मरणपत्र जोडा',
    fertilizerSuggestions: 'खत सूचना',
    aiFertilizerTitle: 'AI खत शिफारसी',
    aiFertilizerSubtitle: 'तुमच्या मातीच्या आरोग्यावर आणि निवडलेल्या पिकांवर आधारित.',
    getAiSuggestions: 'AI सूचना मिळवा',
    fertilizerName: 'खताचे नाव',
    fertilizerQuantity: 'प्रमाण',
    timing: 'वेळ',
    method: 'पद्धत',
    reason: 'कारण',
    noSoilDataForSuggestions: 'अचूक खत सूचना मिळवण्यासाठी कृपया प्रथम तुमचा माती आरोग्य डेटा अपडेट करा.',
    reminderTitle: 'स्मरणपत्र शीर्षक',
    reminderDescription: 'वर्णन (पर्यायी)',
    activityType: 'उपक्रमाचा प्रकार',
    dueDate: 'नियत तारीख',
    fertilizer: 'सेंद्रिय खत',
    harvesting: 'कापणी',
    pesticide: 'कीटकनाशक',
    other: 'इतर',
    noReminders: 'अद्याप कोणतेही स्मरणपत्र सेट केलेले नाही.',
    delete: 'हटवा',
    markAsDone: 'पूर्ण म्हणून चिन्हांकित करा',
    overdue: 'थकीत',
    dueToday: 'आज देय',
    upcoming: 'येणारे',
    phoneNumber: 'फोन नंबर',
    ivrSupport: 'IVR आणि व्हॉइस सपोर्ट',
    ivrSupportSubtitle: 'तुमच्या फोनवर स्वयंचलित व्हॉइस असिस्टन्स आणि स्मरणपत्रे मिळवा.',
    callKisanCenter: 'किसान कॉल सेंटर (टोल फ्री)',
    kisanCenterDesc: 'तज्ञांकडून त्वरित कृषी सल्ल्यासाठी कॉल करा.',
    voiceReminders: 'व्हॉइस स्मरणपत्रे',
    voiceRemindersDesc: 'तुमच्या शेती स्मरणपत्रांसाठी स्वयंचलित कॉल सक्षम करा. तुमचा फोन नंबर वर सेव्ह केल्याची खात्री करा.',
    enabled: 'सक्षम',
    disabled: 'अक्षम',
    fullName: 'पूर्ण नाव',
    saveChanges: 'बदल जतन करा',
    profileUpdated: 'प्रोफाइल अपडेट केली',

    // Marketplace
    marketplaceSubtitle: 'थेट मंडी भाव तपासा, उत्पादनांचा व्यापार करा आणि जागतिक बाजारपेठा शोधा.',
    allStates: 'सर्व राज्ये',
    mandiPrices: 'मंडी भाव',
    buyProducts: 'उत्पादने खरेदी करा',
    myListings: 'माझ्या सूची',
    globalMarkets: 'जागतिक बाजारपेठा',
    searchMandi: 'वस्तू किंवा बाजार शोधा...',
    searchProducts: 'उत्पादने किंवा स्थान शोधा...',
    priceTrends: 'किंमत कल',
    historicalTrend: 'ऐतिहासिक मॉडेल किंमत कल (प्रति क्विंटल)',
    price: 'किंमत',
    min: 'किमान',
    max: 'कमाल',
    modal: 'मॉडेल',
    perQuintal: 'प्रति क्विंटल',
    available: 'उपलब्ध',
    listedBy: 'द्वारे सूचीबद्ध',
    contactSeller: 'विक्रेत्याशी संपर्क साधा',
    noProducts: 'अद्याप विक्रीसाठी कोणतीही उत्पादने सूचीबद्ध केलेली नाहीत.',
    listNewProduct: 'नवीन उत्पादन सूचीबद्ध करा',
    commodity: 'वस्तू',
    quantity: 'प्रमाण',
    dateListed: 'सूचीबद्ध तारीख',
    status: 'स्थिती',
    visitPlatform: 'प्लॅटफॉर्मला भेट द्या',
    realTimeOpportunities: 'रिअल-टाइम विक्रीच्या संधी',
    opportunitiesSubtitle: 'आमच्या पार्टनर नेटवर्कद्वारे थेट घाऊक खरेदीदार, संस्थात्मक बाजारपेठा आणि निर्यात संधींशी कनेक्ट व्हा.',
    exportMarkets: 'निर्यात बाजार',
    bulkBuyers: 'घाऊक खरेदीदार',
    joinNetwork: 'नेटवर्कमध्ये सामील व्हा',
    listProduct: 'उत्पादन सूचीबद्ध करा',
    commodityName: 'वस्तूचे नाव',
    unit: 'एकक',
    kilograms: 'किलोग्राम (किग्रॅ)',
    quintals: 'क्विंटल (१०० किग्रॅ)',
    tons: 'टन',
    dozen: 'डझन',
    pricePerUnit: 'प्रति एकक किंमत',
    pickupLocation: 'पिकअप स्थान',
    noListings: 'तुम्ही अद्याप कोणतीही उत्पादने सूचीबद्ध केलेली नाहीत.',
    enamDesc: 'राष्ट्रीय कृषी बाजार - एक अखिल भारतीय इलेक्ट्रॉनिक ट्रेडिंग पोर्टल.',
    agmarknetDesc: 'थेट किमतींसाठी कृषी विपणन माहिती नेटवर्क.',
    ninjacartDesc: 'शेतकऱ्यांना थेट किरकोळ विक्रेत्यांशी जोडणारी B2B बाजारपेठ.',
    dehaatDesc: 'बाजारपेठेसह शेतकऱ्यांसाठी एंड-टू-एंड सेवा.',
    bighaatDesc: 'भारतातील सर्वात मोठी कृषी-इनपुट बाजारपेठ.',

    // AI Assistant
    aiAssistantName: 'कृषी मित्र एआय',
    onlineReady: 'ऑनलाइन आणि मदतीसाठी तयार',
    assistantWelcome: 'तुमच्या पिकांबद्दल, मातीबद्दल किंवा सरकारी योजनांबद्दल मला काहीही विचारा!',
    exampleQ1: 'चिकण मातीसाठी सर्वोत्तम पीक?',
    exampleQ2: 'पीएम-किसान पात्रता?',
    exampleQ3: 'टोमॅटोच्या पानांवर ठिपके?',
    typeQuestion: 'तुमचा प्रश्न येथे टाइप करा...',

    // Diseases & Pests
    diseasesAndPests: 'रोग आणि कीड',
    pests: 'कीड',
    diseasesSubtitle: 'पीक समस्या ओळखा आणि तज्ञ उपचार सूचना मिळवा.',
    aiDiagnosis: 'AI निदान',
    pestIdentification: 'कीड ओळख',
    pestSigns: 'कीड चिन्हे / लक्षणे',
    pestPlaceholder: 'उदा. पानांना छिद्रे, लहान हिरवे कीडे',
    identifyNow: 'आता ओळखा',
    cropName: 'पिकाचे नाव',
    cropPlaceholder: 'उदा. टोमॅटो, गहू',
    uploadPhoto: 'फोटो अपलोड करा',
    clickToUpload: 'फोटो अपलोड करण्यासाठी क्लिक करा',
    symptomsOptional: 'लक्षणे (पर्यायी)',
    symptomsPlaceholder: 'उदा. पिवळे डाग, कोमेजणे',
    diagnoseNow: 'आता निदान करा',
    diagnosisResult: 'निदान निकाल',
    pestResult: 'कीड ओळखली',
    confidence: 'आत्मविश्वास',
    disease: 'रोग',
    pestName: 'कीड नाव',
    identification: 'ओळख',
    cause: 'कारण',
    immediateRemedy: 'त्वरीत उपचार',
    ecoFriendlyControl: 'पर्यावरणपूरक नियंत्रण',
    prevention: 'प्रतिबंध',
    similarDiseases: 'सारखे रोग',
    addToCropDiary: 'माझ्या पीक डायरीमध्ये जोडा',
    addToPestLog: 'कीड लॉगमध्ये जोडा',
    viewInDatabase: 'डेटाबेसमध्ये पहा',
    clearResults: 'निकाल साफ करा',
    scientificName: 'शास्त्रीय नाव',
    pathology: 'पॅथॉलॉजी',
    treatments: 'उपचार',
    lifeCycle: 'जीवन चक्र',
    chemicalControl: 'रासायनिक नियंत्रण',
    localizedRecommendations: 'स्थानिक शिफारसी',
    multipleImagesHint: 'अधिक अचूकतेसाठी तुम्ही ३ फोटो पर्यंत अपलोड करू शकता.',
    searchDiseaseDatabase: 'रोग डेटाबेस शोधा...',
    searchPestDatabase: 'कीड डेटाबेस शोधा...',
    pestDatabaseComingSoon: 'कीड डेटाबेस लवकरच येत आहे',
    pestDatabaseDesc: 'आम्ही सध्या सामान्य कृषी कीटकांचा सर्वसमावेशक डेटाबेस तयार करत आहोत. त्वरित मदतीसाठी AI निदान साधन वापरा!',
    trending: 'ट्रेंडिंग',
    symptoms: 'लक्षणे',
    viewFullRemedy: 'पूर्ण उपचार पहा',

    // Profile
    farmerProfile: 'शेतकरी प्रोफाइल',
    profileSubtitle: 'तुमची वैयक्तिक माहिती आणि अनेक शेती ठिकाणे व्यवस्थापित करा.',
    personalInfo: 'वैयक्तिक माहिती',
    farmerCategory: 'शेतकरी प्रवर्ग',
    smallFarmer: 'लहान शेतकरी',
    marginalFarmer: 'अल्पभूधारक शेतकरी',
    largeFarmer: 'मोठा शेतकरी',
    aadharLinked: 'आधार लिंक केले आहे',
    aadharRequired: 'बहुतेक सरकारी योजनांसाठी आवश्यक',
    myLands: 'माझ्या जमिनी',
    acres: 'एकर',
    noLands: 'अद्याप जमिनी जोडल्या नाहीत.',
    addNewLand: 'नवीन जमीन जोडा',
    landName: 'जमिनीचे नाव / ओळखकर्ता',
    landNamePlaceholder: 'उदा. उत्तर क्षेत्र, गाव फार्म',
    locationAddress: 'स्थान पत्ता',
    soilType: 'मातीचा प्रकार',
    soilTypePlaceholder: 'उदा. काळी',
    sizeAcres: 'आकार (एकर)',
    addLand: 'जमीन जोडा',
    landStatus: 'जमिनीची स्थिती',
    planted: 'पेरणी झाली',
    empty: 'रिकामी',
    currentCrop: 'सध्याचे पीक',
    enterCurrentCrop: 'सध्याचे पीक प्रविष्ट करा...',

    // General
    ivrAssistant: 'IVR सहाय्यक',
    location: 'स्थान',
    date: 'तारीख',
    sold: 'विकले',
    selectLocationOnMap: 'नकाशावर स्थान निवडा',
    confirmLocation: 'स्थानाची पुष्टी करा',
    currentLocation: 'वर्तमान स्थान',
    latitude: 'अक्षांश',
    longitude: 'रेखांश',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('language');
    return (saved as Language) || 'en';
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('language', lang);
    
    setTimeout(() => {
      const select = document.querySelector('.goog-te-combo') as HTMLSelectElement;
      if (select) {
        select.value = lang;
        select.dispatchEvent(new Event('change'));
      }
    }, 100);
  };

  const t = (key: string): string => {
    // If we have static translations for the language, use them (like for hi, mr)
    // Otherwise fallback to English and let Google Translate translate the DOM.
    const langData = translations[language as any] || translations['en'];
    return langData[key] || translations['en'][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
